- hosts: webservers
  become: yes
  roles:
    - { role: datadog.datadog, become: yes }
  tasks:
    - name: Install Docker
      include_tasks:
        file: ./roles/tasks/install_docker.yml

    - name: Create .env file
      template:
        src: .env.j2
        dest: /.env

    - name: Run Redmin
      become: yes
      docker_container:
        image: redmine:5.0.4-alpine
        name: redmine
        state: started
        auto_remove: true
        env_file: /.env
        ports:
          - "80:3000"
